blank_issues_enabled: false
contact_links:
  - name: MultiViewer Discord Server
    url: https://muvi.gg/discord
    about:
      Please ask your question in the DigiFlag Releases, Issue and FR channel in the MultiViewer Discord under the
      integrations channel.
