name: Test build on Windows

on: [push]

jobs:
    build:
        runs-on: ubuntu-lastest

        steps:
            - uses: actions/checkout@v3

            - name: Build on windows
              run: sh ./build/build_windows.sh
